spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration,classpath:db/testdata

algafood.email.impl=fake

springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.swagger-ui.oauth.client-secret=swagger123
springdoc.swagger-ui.oauth.scopes=READ,WRITE
springdoc.swagger-ui.oauth.use-basic-authentication-with-access-code-grant=true
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.urls-primary-name=AlgaFood API v1