spring.application.name=algafood-api

spring.profiles.default=dev

spring.jpa.open-in-view=false

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.flyway.locations=classpath:db/migration

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

algafood.storage.local.diretorio-fotos=${ALGAFOOD_STORAGE_LOCAL_DIRETORIO_FOTOS:${user.home}/algafood/catalogo}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}

algafood.email.remetente=${MAIL_FROM:AlgaFood <naoresponder@algafood.com.br>}
algafood.email.impl=${MAIL_IMPL:fake}
algafood.email.sandbox.destinatario=${MAIL_SANDBOX_DESTINATARIO:teste@algafood.com.br}

algafood.auth-server.issuer=${AUTH_SERVER_ISSUER:http://localhost:8080}

algafood.jwt.keystore.jks-location=${JWT_KEYSTORE_LOCATION:classpath:keystores/algafood.jks}
algafood.jwt.keystore.password=${JWT_KEYSTORE_PASSWORD:123456}
algafood.jwt.keystore.keypair-alias=${JWT_KEYSTORE_ALIAS:algafood}